### PR TITLE
add Makefile to project

### PR DESCRIPTION
**Pull request by punkkeks**
It is just a simple Makefile but it will make it possible to edit the
library in various IDEs like kdevelop. This is very helpful in my opinion.

### CODE REVIEW

**Comment by punkkeks** [comment]
My fingers were quicker than my mind. I see that scons expects some variables. Nevermind, just to import the project, this makefile is more than enough. If wished, I can handle the variables to pass it from the makefile to scons.

**Comment by mikepurvis** [comment]
Ehh, if you need to hack on stm32plus itself in an IDE, then create that in your local fork. In any case, it looks like there are better ways to handle it in IDEs other than kdevelop:

http://www.scons.org/wiki/IDEIntegration#Integrating_scons_into_IDEs

**Comment by punkkeks** [comment]
http://www.scons.org/wiki/IDEIntegration#How_can_I_set_up_a_project_with_SCons.3F
that's the same resource :) but nevermind. Close it if you want or tell me to fix the variable issue. It's up to you.

**Comment by andysworkshop** [comment]
I tend to agree with Mike that stuff related to an unsupported IDE is best maintained in your own fork so I'll close this for now. Thanks for contributing though and please don't be put off contributing more in the future +1:

**Pull request closed without merging**
